apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  labels:
    app: mediawiki
data:
  apache2.conf: |-
    ServerName localhost
    <VirtualHost *:80>
      DocumentRoot /var/www/html
      <Directory /var/www/html>
        AllowOverride All
        Require all granted
      </Directory>
    </VirtualHost>
