apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mediawiki_password
        - name: MYSQL_DATABASE
          value: mediawiki
        - name: MYSQL_USER
          value: mediawiki_user
        - name: MYSQL_PASSWORD
          value: mediawiki_password

